### ISSUE TITLE
Bring website to production status

### ISSUE THREAD

**Issue by archerbarrie** [FreeUKGen/FreeUKGenealogy#1]
Web site should be run on web servers and made manageable

**Comment by archerbarrie** [comment]
Currently the website is running on the off-site backup server and needs to be moved to the web servers. In addition it needs to be managed in a similar way to other project websites, in particular so any authorised person can amend it.

**Comment by PatReynolds** [comment]
Please split to two stories, as they are quite different. Thanks.

Pat Reynolds
Executive Director, Free UK Genealogy

**Comment by archerbarrie** [comment]
Two issues (#5 and #6) have been raised.
