### ISSUE TITLE
FreeUKGen/Coordination/issues/1010 "Navigation bar broken on FUG site"

### ISSUE THREAD

**Issue by arswright-alt-uk** [FreeUKGen/FreeUKGenealogy#10]
Per @DeniseColbert 

![image](https://user-images.githubusercontent.com/19173257/48774339-dae3b700-ecc1-11e8-90c7-d1cb8dd4fc06.png)

But should look like this:

![image](https://user-images.githubusercontent.com/19173257/48774468-49287980-ecc2-11e8-81af-bc2962d7395e.png)

**Comment by DeniseColbert** [comment]
Could you also add "Volunteer" in to this bar? (to go to https://www.freeukgenealogy.org.uk/about/volunteer/)

**Comment by arswright-alt-uk** [comment]
@DeniseColbert 

> Could you also add "Volunteer" in to this bar? (to go to https://www.freeukgenealogy.org.uk/about/volunteer/)

Will let you handle this through [/admin/globals/header](https://freeukgenealogy.org.uk/admin/globals/header) configuration (that way you can decide where it's placed, etc).

**Comment by DeniseColbert** [comment]
I'd forgotten I could do that, thanks Gray :)

I've added the block, but left if disabled until the bar is fixed as the links overlap the logo. It should fit fine in the box, though.

**Comment by arswright-alt-uk** [comment]
Changes deployed - may need to hard-refresh (<kbd>Ctrl</kbd>+<kbd>F5</kbd>) see changes.

**Comment by DeniseColbert** [comment]
Seems fixed, however, we're missing the search icon:

![image](https://user-images.githubusercontent.com/19173257/49220377-f9d2ff00-f3cd-11e8-93e7-bcd8a32b4bca.png)

**Comment by arswright-alt-uk** [comment]
@DeniseColbert The sprite was probably removed w/the CSS updates - I'll track it down ASAP.

**Comment by DeniseColbert** [comment]
Thanks Gray :)
