### ISSUE TITLE
FreeUKGen/Coordination/issues/868 "Add Tag manager to FUG website"

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKGenealogy#26]
Reference: [Add Tag manager to FUG website](https://github.com/FreeUKGen/Coordination/issues/868)

**Comment by arswright-alt-uk** [comment]
**Reference:** [Use Javascript variable to run `customTask`](https://www.simoahava.com/analytics/trigger-javascript-without-using-custom-html-tag/)

(This method *should* allow for management of all analytics code locally - as opposed to relying upon Google Tag Manager configuration - providing custom configurability w/o adding significantly to DOM render)

**Comment by DeniseColbert** [comment]
Maybe @richpomfret can provide advice on this?

**Comment by dhousman** [comment]
Hi,

I'm trying to get up to speed on this issue, so I"m trying to put this all together.. I think what you're saying is that you want to use two containers on each page, one with stuff that all the sites have in common, and another with stuff that's just for the current page. Is that correct?

I agree that this would save some work becasue there are commonalities between the different sites, however I worry that doing this would reduce the flexibility to modify the tags on a site by site basis. I also think that in the long run, keeping things separate will reduce the complexity and overhead of managing implementations in 4 properties in GTM. 

I agree that GTM will will make it possible to reduce reliance on changes to the local codebase. 

Do I understand your suggestion currectly? Does that address your question? 

Thanks,
David

**Comment by dhousman** [comment]
@arswright @DeniseColbert

**Comment by arswright-alt-uk** [comment]
@dhousman 

> I think what you're saying is that you want to use two containers on each page, one with stuff that all the sites have in common, and another with stuff that's just for the current page. Is that correct?

No, this would be two separate GTM workspaces for FUG specifically - the idea here is to do away with on-site Javascript analytics configuration (no cookies/GDPR decline scenario versus typical analytics configuration).

**Comment by dhousman** [comment]
Hi,

Thank for your correction... I think I’m out of the loop here.  let me make
sure I understand... is this related to the issue I brought up with the
analytics request not getting fired when people haven’t accepted the cookie
statement?

 Are you writing custom code that determines when the analytics request
gets fired?

Thanks,
David

**Comment by arswright-alt-uk** [comment]
@dhousman

> is this related to the issue I brought up with the analytics request not getting fired when people haven’t accepted the cookie statement?

That's a valid issue, though I was not considering it in making the recommendation.

> Are you writing custom code that determines when the analytics request
gets fired?

I'm using the code indicated on the first comment to this issue; [FreeUKGen/Coordination/issues/868](https://github.com/FreeUKGen/Coordination/issues/868) provides further background discussion.

**Comment by arswright-alt-uk** [comment]
Received June 2019 - Product Update for Google Tag Manager with link to [guide by Simo Ahava](https://www.simoahava.com/analytics/custom-templates-guide-for-google-tag-manager/) which describes how to create custom variable templates for use within GTM, should be able to resolve my concerns about maintaining custom Javascript in GTM to support toggled Google Analytics features. 

References:

* [`getCookieValues`](https://developers.google.com/tag-manager/templates/api#getcookievalues) API
* [`anonymizeIp`](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#anonymizeIp) GA/UA configuration variable
* [`allowAdFeatures`](https://support.google.com/analytics/answer/9050852?hl=en) GA/UA configuration variable
* [Capture outbound links](https://support.google.com/analytics/answer/1136920?hl=en) / [Google Analytics events](https://support.google.com/tagmanager/answer/6106716) for outbound link tracking

**Comment by arswright-alt-uk** [comment]
@DeniseColbert Looking to implement and test on this issue, however, I do not have permissions to create a separate Property in Google Analytics for viewing testing activity separately of production data and the "FreeUKGen DEV" View on the production Property is just a view on production data - to the best of my knowledge, I need a separate Property ID to achieve any meaningful distinction between activities on DEV and PRD environments.

**Comment by DeniseColbert** [comment]
I just gave you Edit access, I think that should let you proceed.

**Comment by arswright-alt-uk** [comment]
@DeniseColbert It appears as though I now have "Edit" permissions for the Property, however, I would need "Edit" permissions for the Account to create a new property per [Google Analytics user permissions](https://support.google.com/analytics/answer/2884495?hl=en).

![Screenshot from 2019-06-26 03-50-15](https://user-images.githubusercontent.com/45101687/60174671-637d8500-97c6-11e9-8e14-064e80c51a91.png)

**Comment by DeniseColbert** [comment]
Done; sorry! I wondered why properties weren't mentioned.

**Comment by DeniseColbert** [comment]
I've opened an epic for this for WP site and referenced this story- closing.
