### ISSUE TITLE
Review website technology

### ISSUE THREAD

**Issue by archerbarrie** [FreeUKGen/FreeUKGenealogy#3]
The Free UK Genealogy website is run on commercial technology (Craft Pro) whereas all other technology used by FreeUKGen projects is Open Source. The suspicion is that it was expedient to use the commercial technology ("it seemed like a good idea at the time") without consideration of FreeUKGen policy. A documented decision needs to be made to either stay with the current technology or move to Open Source (e.g. WordPress).

**Comment by DeniseColbert** [comment]
Review underway

**Comment by arswright-alt-uk** [comment]
I'm advocating for WordPress 5.0 as a replacement for Craft CMS on the basis that WordPress 5.0 is open source, provides same functionality as Craft CMS, has a far greater contributor userbase (more freely-available code via plugins to cover feature requirements, better development and support documentation), and will be more readily-usable to new users and those with prior CMS experience.

I will set milestones for implementation of a WordPress 5.0 prototype in the dev/test environment, template and content import from Craft CMS, and test/approval promotion process to complete the transition and, barring any objections, begin work on this process.

**Comment by Captainkirkdawson** [comment]
I would support that move

**Comment by PatReynolds** [comment]
I have just had a very brief look at Wordpress 5.0 - gosh, that's new! - and it seems to fit our bill very well (from a content contributor perspective).

**Comment by DeniseColbert** [comment]
Decision will be sought from Trustees at meeting 19/1

**Comment by PatReynolds** [comment]
Please add link in agenda to document.

**Comment by DeniseColbert** [comment]
Have asked Gray if there is a document, will do so if there is.
