### ISSUE TITLE
c9.io TEST2 and TEST3 instances

### ISSUE THREAD

**Issue by arswright-alt-uk** [FreeUKGen/FreeUKGenealogy#38]
1. Get up to speed on c9.io operations
2. Implement TEST2 and TEST3 instances
3. Document workflows

**Comment by arswright-alt-uk** [comment]
Progress:

[x] Get up to speed on c9.io operations
[x] Clone arswright-alt-uk/FreeUKGenealogy to https://ide.c9.io/arswright/dev-freeukgenealogy-craft workspace
[x] Import database
[x] Configure `/etc/apache2/sites-available/001-cloud9.conf`
[ ] Working test environment (left off at database selection error as reported by Craft CMS)

**Comment by arswright-alt-uk** [comment]
Process repeated for https://staging-freeukgenealogy-craft-arswright.c9users.io/ (u: `preview` / p: `preview`) and TEST3 instance confirmed working.

@DeniseColbert Now that TEST2 (repository: arswright/FreeUKGenealogy) and TEST3 (repository: FreeUKGen/FreeUKGenealogy) are set up we can perform destructive testing at either instance.

It does not appear as though `test2.freeukgenealogy.org.uk` or `test3.freeukgenealogy.org.uk` are set up in forward DNS (instead, we are presently using dev-freeukgenealogy-craft-arswright.c9users.io for TEST2 and staging-freeukgenealogy-craft-arswright.c9users.io for TEST3) - marking this issue closed but please reopen and advise if additional action is required.

**Comment by DeniseColbert** [comment]
Have you seen this @arswright-alt-uk ?

![image](https://user-images.githubusercontent.com/19173257/55621449-6fdcdd80-5795-11e9-8abf-534bf9779970.png)

**Comment by arswright-alt-uk** [comment]
@DeniseColbert  I hadn't received this email yet - will await resolution on https://github.com/FreeUKGen/Coordination/issues/1131

**Comment by PatReynolds** [comment]
@arswright-alt-uk if you have a preferred solution (or advice to avoid something) please do let us know.

**Comment by arswright-alt-uk** [comment]
@PatReynolds I'm not aware of any limitations which would prevent us from running dev, test, and staging instances of the application on the production AWS instance (though obviously care would need to be taken to ensure isolation between development and production databases).

**Comment by PatReynolds** [comment]
Thanks, @arswright-alt-uk .  @richpomfret may elucidate, but we are trying to separate Test and Production.  It may not be so much of an issue for the F U G website.

**Comment by arswright-alt-uk** [comment]
New issue on task of test server setup at FreeUKGen/Coordination/issues/867

**Comment by richpomfret** [comment]
Imo, it makes sense to replicate the test2/test3 format we follow for all of our other sites. I am still exploring just how we use Cloud9 (the AWS version - which does use EC2 instances for dev environments). In which case, the workflow in the past has involved setting up workspaces - @Captainkirkdawson or @benwbrum can clarify here.

**Comment by Captainkirkdawson** [comment]
We want the developer to run in their own workspace not a common one.
I see no need to have 2 workspaces such as test2/3. There is no difference in code. Their only difference is that test2 runs under rails as development environment and uses a development database. test3 as a production environment and a production style database (sharded in the case of REG)
Any code set can be run as development or production do there is no need for the complexity being proposed.

**Comment by arswright-alt-uk** [comment]
Added `mod_auth` (u:test/p:test) access restriction to discourage search engine indexing of test instances.

@richpomfret My understanding (per [this comment from Denise](https://app.zenhub.com/workspaces/freeukgenealogysite-5cfdeab6c34c1b37ca337cab/issues/freeukgen/freeukgenealogy/38#issuecomment-480226266)) was that we needed a replacement for the discontinued C9.io - if the plan is to continue using the AWS Cloud9 platform for testing, shouldn't these instances be set up under AWS Cloud9? (Either way, I develop locally and would only be using `test2` and `test3` for acceptance testing w/Denise and staging w/the CMS migration)

**Comment by arswright-alt-uk** [comment]
@DeniseColbert OK to close if you would please confirm that you are able to access test instances with username `test` / password `test`

**Comment by DeniseColbert** [comment]
Test2 worked fine, test3 just showed me the screen; didn't require login.

**Comment by arswright-alt-uk** [comment]
@DeniseColbert Ah, I added authentication directives to the `http://` virtualhost, not the `https://`one (worked in testing against `http://test3.freeukgenealogy.org.uk/` but obviously not w/SSL).

Please re-test to confirm working at this time - my apologies for the oversight!

**Comment by DeniseColbert** [comment]
No worries, that fixed it :)

**Comment by arswright-alt-uk** [comment]
Access confirmed per @DeniseColbert - no further action on issue at this time.
