### ISSUE TITLE
Bug: Giftaid form is not sending to Helen V.

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKGenealogy#39]
We have a form where people can declare that their donation is eligible for giftaid - it should send an email to Helen Vince informing her, so she can add the giftaid information to donations by bank transfer, cheque, etc.  
Part 1: can this be made to work?

**Comment by PatReynolds** [comment]
That's the one!  Sorry for not including it before.

**Comment by arswright-alt-uk** [comment]
Bumping this and related issue #40  to the top of my stack for investigation.

**Comment by arswright** [comment]
Investigation in progress:

1. `/admin/sproutforms/entries` administration page shows all `Gift Aid Declaration` results available w/search for "gift"
2. `/admin/sproutforms/forms/edit/474` administration page shows form `giftAidDeclaration` declaration configured to email Helen
3. Last `giftAidDeclaration` form submission occurred Tue, 04 Dec 2018 12:14:44 (though prior submission occurred Mon, 15 Oct 2018 15:24:30)

Happy to take further action on this issue, though - given that everything appears to be configured correctly and submissions are seldom in nature - I would like to (a) confirm the correct email address for Helen and (b) ask that Helen submit an entry on the form herself and confirm that no email is delivered within 2 hours.

Once we have confirmed the correct destination email and that the form is not issuing notifications as configured, I can proceed with email troubleshooting.

Will proceed with related issue Bug: Giftaid form is not sending to Helen V. #40  for the time being.

**Comment by PatReynolds** [comment]
Helen reports she has successfully received  the email with the data she put into the form.

**Comment by arswright-alt-uk** [comment]
@PatReynolds I received a copy as well - removing my address from notification contacts now.

Closing out as we were unable to replicate the issue.
