### ISSUE TITLE
Bug: Giftaid form has not been sending to Helen V.

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKGenealogy#40]
See 39 - is it possible to export and send the data from previous forms to Helen, or re-send the emails?

**Comment by arswright** [comment]
I show a user account for Helen at Craft CMS admin [Users](https://www.freeukgenealogy.org.uk/admin/users) page (last login: 2018-09-13) and all information pertaining to Gift Aid Declaration form submissions is available at [Forms](https://www.freeukgenealogy.org.uk/admin/sproutforms/entries) page by searching "gift" - will existing access be sufficient for Helen to proceed, or would a spreadsheet export be preferable?

**Comment by PatReynolds** [comment]
Thanks, @arswright-alt-uk  a spreadsheet would be preferable. I'll put Helen's email address on slack.

**Comment by arswright** [comment]
@PatReynolds Confirmed that email address provided via Slack is configured as user account contact for Helen and notification recipient for Gift Aid Declaration form.

Added my own contact email address to notifications for Gift Aid Declaration form (should now notify both of us) so I should receive a notification as well when Helen tests.

**Comment by arswright-alt-uk** [comment]
@PatReynolds Shared raw .CSV database export + formatted Google Sheets version (all records) with Helen per request, closing issue.

**Comment by PatReynolds** [comment]
thank you very much!
