### ISSUE TITLE
Prevent contact form spam

### ISSUE THREAD

**Issue by arswright-alt-uk** [FreeUKGen/FreeUKGenealogy#42]
Per @DeniseColbert incoming form spam is occurring despite [Sprout Invisible CAPTCHA](https://sprout.barrelstrengthdesign.com/craft-plugins/invisible-captcha) implementation.

Investigate current CAPTCHA settings to reduce incidence of form spam after reviewing `sproutinvisiblecaptcha.log` runtime logs to determine why spam messages were allowed through.

**Comment by arswright-alt-uk** [comment]
Investigating why "Prevent duplicate submissions if a user hits submit more than once" was not enabled.

**Comment by Captainkirkdawson** [comment]
On FreeREG we use hidden fields to trap bots as well as speed of filling

**Comment by arswright-alt-uk** [comment]
@Captainkirkdawson The Sprout Invisible CAPTCHA plugin does something similar, though it's very limited in what it logs (e.g. doesn't log originating IP) and doesn't check IP/ASN against known spam originators - definitely room for improvement there.

**Comment by arswright-alt-uk** [comment]
Per discussion w/Bev, enabled "Prevent duplicate submissions if a user hits submit more than once" option for Sprout Invisible CAPTCHA plugin.

Investigating message blocking by matched string.
