### ISSUE TITLE
Craft Transfer to AWS

### ISSUE THREAD

**Issue by archerbarrie** [FreeUKGen/FreeUKGenealogy#5]
The website needs to be moved to the production webs servers

**Comment by arswright-alt-uk** [comment]
Per @lemon-ukgen freeukgenealogy.org.uk is on production hardware and has backup implementation, however, there is no redundancy/fail over at this time.

Issue open for further comment and follow-up as [AWS](https://github.com/FreeUKGen/Coordination/issues/867) options are explored.

**Comment by archerbarrie** [comment]
The issue is "bring website to production status" which involves more than just the particular hardware it is being run on. For example, it also covers documentation, monitoring, management and fail-over. So, if the software stopped working, and lemon was not available, where would one start to try to fix it?

**Comment by arswright** [comment]
@archerbarrie Great points - I'll be generating documentation for everything I do, will leave question of sysadmin processes to @lemon-ukgen

**Comment by arswright-alt-uk** [comment]
Renaming this task from "Move website to production servers" to "Craft Transfer to AWS" (transfer to AWS should accomplish objective), pending prioritization by @DeniseColbert

**Comment by DeniseColbert** [comment]
Is this done now?

**Comment by arswright-alt-uk** [comment]
@DeniseColbert Ah sorry - yes, all hosted services are now at AWS, closing out.
