### ISSUE TITLE
Compress CSS

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeUKGenealogy#54]
css indented and is slowing down our site speed.

**Comment by arswright-alt-uk** [comment]
@DeniseColbert This should be accomplished using `mod_deflate`, not by making changes to CSS (or JS) files - will investigate server configuration and relay any changes to Lemon.

**Comment by arswright-alt-uk** [comment]
Updated apache24 configuration, notified Lemon to enable `mod_deflate` in Puppet configuration.
