### ISSUE TITLE
Change text color #444 to #222

### ISSUE THREAD

**Issue by arswright-alt-uk** [FreeUKGen/FreeUKGenealogy#58]
High priority change per @DeniseColbert in [FreeUKGen/Coordination/issues/1234](https://github.com/FreeUKGen/Coordination/issues/1234)

**Comment by arswright-alt-uk** [comment]
@DeniseColbert Change available for Review/QA at https://test2.freeukgenealogy.org.uk/

**Comment by DeniseColbert** [comment]
Not sure if this is my eyes but I can't see a difference:
![image](https://user-images.githubusercontent.com/19173257/60051844-d7873280-96cb-11e9-84b5-b8b36b2a5d8a.png)

Will try again after sleep!

**Comment by arswright-alt-uk** [comment]
@DeniseColbert If the [gamma settings](https://www.laptopmag.com/articles/calibrate-monitor-windows-10) on your monitor aren't properly set there may be no perceivable difference - given the scale and width of the font, true black would have the best readability.

A Photoshop point sample (or right-click on paragraph and select "Inspect element" in Chrome) will confirm the change:

![190624-222_vs_444](https://user-images.githubusercontent.com/45101687/60054108-77be6680-968e-11e9-8870-76ca5a54d5cf.jpg)

![Screenshot from 2019-06-24 14-46-07](https://user-images.githubusercontent.com/45101687/60054264-d683e000-968e-11e9-95f3-593c898c37bf.png)

**Comment by DeniseColbert** [comment]
Thanks for that Gray, I calibrated my colour settings and now I can see the difference (my laptop screen resolution isn't great so I should have checked on the desktop anyway).

**Comment by arswright-alt-uk** [comment]
@DeniseColbert The imperceivable difference for non-calibrated monitors is going to remain a readability issue for (probably) most users who've historically had difficulty reading site text - shall we switch to true black?

**Comment by DeniseColbert** [comment]
I agree, but I know that we've done a lot of work on the colours in light of our accessibility review by an external agency and so I think #222 will have been considered the colour to go for. I'm having a Meet with Alison tomorrow about other design stuff so I'll ask about this and let you know.

**Comment by DeniseColbert** [comment]
True black is too stark and would cause problems for anyone using the websites for a length of time (e.g. project coordinators). #222 is the darkest we can have the text without having a detrimental effect on other things. @AlOneill did find an issue a while back with our font file and how browsers were interpreting it, so, maybe we could check that aspect?

Another thing to consider might be changing the text on THIS site to true black since people don't spend very long on it, compared to the others, but it's important that the text is readable (especially the Donate pages).

**Comment by arswright-alt-uk** [comment]
@DeniseColbert The font in use is [Source Sans Pro (Light)](https://fonts.google.com/specimen/Source+Sans+Pro) - we could switch to Source Sans Regular for better visibility without significantly altering the aesthetics (given that we have a known usability issue affecting donors, I don't think there's an argument to be made for prioritizing aesthetics over usability).

**Comment by DeniseColbert** [comment]
I like the sound of that solution, I'll make a story on the Coordination board and get Pat's thoughts.

**Comment by arswright-alt-uk** [comment]
@DeniseColbert OK - as we have confirmed that the change was implemented (even though it may not be perceptible in some cases) can we consider this change request approved for promotion to production?

**Comment by DeniseColbert** [comment]
Yes, go ahead please, @arswright. I'll open another story if/when appropriate.

**Comment by arswright-alt-uk** [comment]
Promoted to production - closing out.

**Comment by AlOneill** [comment]
The text colour change is showing OK, but there is a narrow (#)444 rectangle at the top of the About page (at least) — seems to be body background colour set at line 9 of _main.scss

**Comment by arswright-alt-uk** [comment]
@AlOneill Unrelated issue prioritized in #33
